/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "OscVoice.h"

//==============================================================================
SynthPlugin2015AudioProcessor::SynthPlugin2015AudioProcessor() : mNumVoices(4)
{
    // add our voices
    for (int i = 0; i < mNumVoices; i++){
        mSynth.addVoice(new OscVoice());
    }
    // clear the synth sounds
    mSynth.clearSounds();
    mSynth.addSound(new OscSound());
}

SynthPlugin2015AudioProcessor::~SynthPlugin2015AudioProcessor()
{
}

//==============================================================================
const String SynthPlugin2015AudioProcessor::getName() const
{
    return JucePlugin_Name;
}

const String SynthPlugin2015AudioProcessor::getInputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

const String SynthPlugin2015AudioProcessor::getOutputChannelName (int channelIndex) const
{
    return String (channelIndex + 1);
}

bool SynthPlugin2015AudioProcessor::isInputChannelStereoPair (int index) const
{
    return true;
}

bool SynthPlugin2015AudioProcessor::isOutputChannelStereoPair (int index) const
{
    return true;
}

void SynthPlugin2015AudioProcessor::prepareToPlay(<#double sampleRate#>, <#int samplesPerBlock#>)

bool SynthPlugin2015AudioProcessor::acceptsMidi() const
{
   #if JucePlugin_WantsMidiInput
    return true;
   #else
    return false;
   #endif
}

bool SynthPlugin2015AudioProcessor::producesMidi() const
{
   #if JucePlugin_ProducesMidiOutput
    return true;
   #else
    return false;
   #endif
}

bool SynthPlugin2015AudioProcessor::silenceInProducesSilenceOut() const
{
    return false;
}

double SynthPlugin2015AudioProcessor::getTailLengthSeconds() const
{
    return 0.0;
}

int SynthPlugin2015AudioProcessor::getNumPrograms()
{
    return 1;   // NB: some hosts don't cope very well if you tell them there are 0 programs,
                // so this should be at least 1, even if you're not really implementing programs.
}

int SynthPlugin2015AudioProcessor::getCurrentProgram()
{
    return 0;
}

void SynthPlugin2015AudioProcessor::setCurrentProgram (int index)
{
}

const String SynthPlugin2015AudioProcessor::getProgramName (int index)
{
    return String();
}

void SynthPlugin2015AudioProcessor::changeProgramName (int index, const String& newName)
{
}

//==============================================================================
void SynthPlugin2015AudioProcessor::prepareToPlay (double sampleRate, int samplesPerBlock)
{
    // Use this method as the place to do any pre-playback
    // initialisation that you need..
}

void SynthPlugin2015AudioProcessor::releaseResources()
{
    // When playback stops, you can use this as an opportunity to free up any
    // spare memory, etc.
}

void SynthPlugin2015AudioProcessor::processBlock (AudioSampleBuffer& buffer, MidiBuffer& midiMessages)
{
    // In case we have more outputs than inputs, this code clears any output
    // channels that didn't contain input data, (because these aren't
    // guaranteed to be empty - they may contain garbage).
    // I've added this to avoid people getting screaming feedback
    // when they first compile the plugin, but obviously you don't need to
    // this code if your algorithm already fills all the output channels.
    for (int i = getNumInputChannels(); i < getNumOutputChannels(); ++i)
        buffer.clear (i, 0, buffer.getNumSamples());
    
    // store numsamples from buffer
    const int numSamples = buffer.getNumSamples();
    
    // Update keyboard state
    mKeyboardState.processNextMidiBuffer(midiMessages, 0, numSamples, true);
    
    // Pass main audio and midi buffer to our synth so it can added its output
    mSynth.renderNextBlock(buffer, midiMessages, 0, numSamples);
    
    /*
    // This is the place where you'd normally do the guts of your plugin's
    // audio processing...
    for (int channel = 0; channel < getNumInputChannels(); ++channel)
    {
        float* channelData = buffer.getWritePointer (channel);

        // ..do something to the data...
    }
    */
}

//==============================================================================
bool SynthPlugin2015AudioProcessor::hasEditor() const
{
    return true; // (change this to false if you choose to not supply an editor)
}

AudioProcessorEditor* SynthPlugin2015AudioProcessor::createEditor()
{
    return new SynthPlugin2015AudioProcessorEditor (*this);
}

//==============================================================================
void SynthPlugin2015AudioProcessor::getStateInformation (MemoryBlock& destData)
{
    // You should use this method to store your parameters in the memory block.
    // You could do that either as raw data, or use the XML or ValueTree classes
    // as intermediaries to make it easy to save and load complex data.
}

void SynthPlugin2015AudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    // You should use this method to restore your parameters from this memory block,
    // whose contents will have been created by the getStateInformation() call.
}

//==============================================================================
// This creates new instances of the plugin..
AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new SynthPlugin2015AudioProcessor();
}

void SynthPlugin2015AudioProcessor::setAttack(float attack){
    for (int i = 0; i < mNumVoices; i++){
        static_cast<OscVoice*>(mSynth.getVoice(int)->setAttack(attack);
    }
    
}

void SynthPlugin2015AudioProcessor::setSustain(float sustain){
    for (int i = 0; i < mNumVoices; i++){
        static_cast<OscVoice*>(mSynth.getVoice(int)->setSustain(sustain);
    }
}

void SynthPlugin2015AudioProcessor::setDecay(float decay){
    for (int i = 0; i < mNumVoices; i++){
        static_cast<OscVoice*>(mSynth.getVoice(int)->setDecay(decay);
    }
}

void SynthPlugin2015AudioProcessor::setRelease(float release){
    for (int i = 0; i < mNumVoices; i++){
        static_cast<OscVoice*>(mSynth.getVoice(int)->setRelease(release)
    }
}
