/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class SynthPlugin2015AudioProcessorEditor  : public AudioProcessorEditor,
Slider::Listener,
Timer,
Button::Listener
{
public:
    SynthPlugin2015AudioProcessorEditor (SynthPlugin2015AudioProcessor&);
    ~SynthPlugin2015AudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    
    void sliderValueChanged(Slider* sliderThatWasChanged);
    void buttonClicked(Button* buttonThatWasClicked);
    
    void timerCallback();

private:
    
    ScopedPointer<MidiKeyboardComponent> mMidiKeyboard;
    
    ScopedPointer<Slider> attackSlider;
    ScopedPointer<Slider> decaySlider;
    ScopedPointer<Slider> sustainSlider;
    ScopedPointer<Slider> releaseSlider;
    
    ScopedPointer<TextButton> sineRadio;
    ScopedPointer<TextButton> sawRadio;
    ScopedPointer<TextButton> squareRadio;
    ScopedPointer<TextButton> triangleRadio;
    
    ScopedPointer<TextButton> saveSettings;
    ScopedPointer<TextButton> loadSettings;
    
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    SynthPlugin2015AudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (SynthPlugin2015AudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
